// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgoxmiimrdbbkonicfqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnb3htaWltcmRiYmtvbmljZnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDYyNzUsImV4cCI6MjA2Nzc4MjI3NX0.pJa_VdMyL4zIhe4UctL-uQz1b2Ne7xezm-aakhmyCak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});