// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdouuyptvtiznnoviskm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkb3V1eXB0dnRpem5ub3Zpc2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzM2MzgsImV4cCI6MjA2NjQwOTYzOH0.RG4Mya5eN0YddkCmGqc7667smhcqBb_ZR_EJ3tw7hOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});